In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

In [3]:
import sys
sys.version

'3.12.6 (tags/v3.12.6:a4a2d2b, Sep  6 2024, 20:11:23) [MSC v.1940 64 bit (AMD64)]'

# CREATING ARRAY

In [4]:
m1=[1,2,3,4,5]
m1

[1, 2, 3, 4, 5]

In [5]:
type(m1)

list

# convert list to array

In [10]:
arr=np.array(m1)
arr

array([1, 2, 3, 4, 5])

In [11]:
type(arr)

numpy.ndarray

In [12]:
type(m1)

list

np.   # numpy contains 217 functions

In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(3.0)

array([0., 1., 2.])

In [17]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [26]:
np.arange(10,20)    # 1 arg should be less than 2 arg    # 1st arg is start index and 2nd arg is end index

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [27]:
np.arange(20,10) # if 2 arg is greater than 1 arg then it prints an empty array

array([], dtype=int32)

In [28]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [30]:
ar=np.arange(-20,-10)
ar

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [31]:
np.arange(10,10)

array([], dtype=int32)

In [32]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [33]:
np.arange(10,30,3)

array([10, 13, 16, 19, 22, 25, 28])

In [34]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [35]:
np.zeros(10,dtype=int)    # hyperparameter tuning(fine tuning)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [36]:
np.zeros([2,2],dtype=int)

array([[0, 0],
       [0, 0]])

In [37]:
a=np.zeros([2,2],dtype=int)
print(a)
print(type(a))

[[0 0]
 [0 0]]
<class 'numpy.ndarray'>


In [39]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [41]:
np.zeros((10,30) ,dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [42]:
np.ones(3)

array([1., 1., 1.])

In [43]:
np.ones(3,dtype=int)

array([1, 1, 1])

In [44]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [45]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [47]:
np.twos((2,3))

AttributeError: module 'numpy' has no attribute 'twos'

In [48]:
rand(3,2)

NameError: name 'rand' is not defined

In [49]:
random.rand(3,2)

NameError: name 'random' is not defined

In [50]:
np.random.rand(3,2)

array([[0.80376028, 0.26098364],
       [0.57353118, 0.6955577 ],
       [0.51551801, 0.51362035]])

In [58]:
np.random.rand(5)

array([0.97257312, 0.31087664, 0.9310983 , 0.18086836, 0.14094915])

In [59]:
np.rand(5)

AttributeError: module 'numpy' has no attribute 'rand'

In [73]:
np.random.rand(1,1)


array([[0.67979686]])

In [74]:
np.random.rand(3,5)

array([[0.49376271, 0.83958796, 0.94396909, 0.189956  , 0.81273097],
       [0.78525322, 0.44796118, 0.52617726, 0.08479368, 0.095686  ],
       [0.38066982, 0.94759885, 0.4257097 , 0.08833941, 0.4488092 ]])

In [64]:
np.random.randint(3,5)

4

In [77]:
np.random.randint(1,20) # 2nd arg is excluded

11

In [76]:
np.random.randint(10,20,4)  # any 4 numbers between 10 and 20

array([12, 15, 16, 15])

In [78]:
np.random.randint(30,20,3)

ValueError: low >= high

In [79]:
np.random.rand(3)

array([0.43229203, 0.43645507, 0.16177218])

In [81]:
np.random.randint(10,40,(10,10))   #3rd arg is considered as a matrix with 10 rows 10 columns with the numbers between 10 and 40

array([[27, 25, 32, 34, 18, 20, 27, 11, 29, 10],
       [29, 27, 32, 32, 13, 24, 30, 36, 22, 35],
       [26, 27, 19, 26, 38, 37, 39, 29, 20, 10],
       [24, 13, 23, 20, 15, 36, 30, 36, 23, 36],
       [39, 23, 22, 15, 15, 32, 14, 19, 10, 33],
       [30, 21, 15, 32, 13, 10, 16, 36, 35, 32],
       [20, 16, 36, 26, 15, 19, 24, 35, 15, 14],
       [24, 26, 12, 21, 32, 31, 11, 29, 12, 23],
       [25, 27, 32, 12, 12, 22, 33, 36, 27, 33],
       [32, 10, 27, 35, 30, 39, 37, 19, 19, 12]])

In [82]:
np.arange(10,26)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

In [83]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [88]:
np.arange(20,40).reshape(4,5)

array([[20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [89]:
np.arange(20,40).reshape(10,2)

array([[20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39]])

In [91]:
np.arange(20,40).reshape(20,1)

array([[20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29],
       [30],
       [31],
       [32],
       [33],
       [34],
       [35],
       [36],
       [37],
       [38],
       [39]])

In [93]:
np.arange(20,40).reshape(5,4)

array([[20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39]])

In [94]:
a=np.arange(20,40).reshape(5,4)
a

array([[20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39]])

In [95]:
a[1][3]

27

In [98]:
a[0:3]

array([[20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

# slicing in matrix

In [99]:
b=np.random.randint(10,20,(5,4))
b

array([[10, 19, 17, 16],
       [17, 18, 11, 11],
       [16, 11, 11, 15],
       [11, 11, 15, 19],
       [19, 11, 18, 19]])

In [100]:
type(b)

numpy.ndarray

In [101]:
b[:]

array([[10, 19, 17, 16],
       [17, 18, 11, 11],
       [16, 11, 11, 15],
       [11, 11, 15, 19],
       [19, 11, 18, 19]])

In [102]:
b[1:4]

array([[17, 18, 11, 11],
       [16, 11, 11, 15],
       [11, 11, 15, 19]])

In [105]:
b[0:4:3]   #[start:stop:step]

array([[10, 19, 17, 16],
       [11, 11, 15, 19]])